#!/usr/bin/env python
#-*- coding:utf-8; mode:python; indent-tabs-mode: nil; c-basic-offset: 2; tab-width: 2 -*-

def rebuild_subdirs():
  return [
    'fiber/build.py',
    'fructose/build.py',
    'libs/libpotato/build.py',
    'libs/libstarch/build.py',
    'orange/build.py',
    'tools/tbar/build_100.rebc',
#    'tools/tbar/build_101.py',
    'tools/tfoo/build.rebc',
    'tools/tbaz/build.rebc',
  ]
