#!/usr/bin/env python
#-*- coding:utf-8; mode:python; indent-tabs-mode: nil; c-basic-offset: 2; tab-width: 2 -*-

def rebuild_subdirs():
  return [
    'fiber/build.py',
    'fructose/build.py',
    'libs/libpotato/build.py',
    'libs/libstarch/build.py',
    'orange/build.py',
    'tools/tbar/build.py',
    'tools/tfoo/build.py',
  ]
